#!/usr/bin/env python3
"""Regenerate the pinned Unicode 16.0 full (C + F, non-Turkic) case-fold table.

Pass a local CaseFolding-16.0.0.txt path to regenerate without network access.
The compiled app requires neither Python nor network access.
"""
import hashlib
from pathlib import Path
import sys
import urllib.request

URL = "https://www.unicode.org/Public/16.0.0/ucd/CaseFolding.txt"
SHA256 = "6f1f9c588eb4a5c718d9e8f93b782685e5c7fec872cf05e8e6878053599e09bb"
data = Path(sys.argv[1]).read_bytes() if len(sys.argv) > 1 else urllib.request.urlopen(URL).read()
assert hashlib.sha256(data).hexdigest() == SHA256, "Unexpected Unicode data version"
entries = {}
for line in data.decode("utf-8").splitlines():
    fields = line.split("#", 1)[0].split(";")
    if len(fields) < 3 or fields[1].strip() not in ("C", "F"):
        continue
    codepoint = int(fields[0].strip(), 16)
    if codepoint < 128:  # ASCII has an inline fast path.
        continue
    mapped = [int(value, 16) for value in fields[2].split()]
    assert 1 <= len(mapped) <= 3
    entries[codepoint] = mapped + [0] * (3 - len(mapped))
lines = [
    "// Generated by tests/generate_unicode_casefold.py; Unicode 16.0.0.",
    "// Source: " + URL,
    "// SHA256: " + SHA256,
    "// Copyright © 2024 Unicode, Inc. See Resources/Unicode-LICENSE.txt (Unicode License V3).",
    "#ifndef VM_UNICODE_CASE_FOLD_DATA_HPP",
    "#define VM_UNICODE_CASE_FOLD_DATA_HPP",
    "#include <cstdint>",
    "namespace VMCore { namespace StringSearchDetail {",
    "struct CaseFoldEntry { uint32_t scalar; uint32_t folded[3]; };",
    "static constexpr CaseFoldEntry caseFoldTable[] = {",
]
for scalar, folded in sorted(entries.items()):
    values = ", ".join(f"0x{value:X}" for value in folded)
    lines.append(f"  {{0x{scalar:X}, {{{values}}}}},")
lines += ["};", "} }", "#endif", ""]
output = Path(__file__).resolve().parents[1] / "src/memory/core/UnicodeCaseFoldData.hpp"
output.write_text("\n".join(lines), encoding="utf-8")
print(f"Generated {len(entries)} Unicode case-fold entries: {output}")
